version: '3.8'

services:
  # 1. SERVIÇO DO BANCO DE DADOS (DB)
  db:
    image: mariadb:latest
    container_name: glpi-db-compose
    volumes:
      - ./glpi-db-data:/var/lib/mysql
    environment:
      # *** AS VARIÁVEIS AQUI DEFINEM O BANCO DE DADOS***
      MARIADB_ROOT_PASSWORD: root_pass_segura
      MARIADB_USER: ${GLPI_DB_USER}
      MARIADB_PASSWORD: ${GLPI_DB_PASSWORD}
      MARIADB_DATABASE: ${GLPI_DB_NAME}
    restart: unless-stopped

  # 2. SERVIÇO DO GLPI (APP)
  glpi:
    image: glpi/glpi:latest
    container_name: glpi-app-compose
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./storage/glpi:/var/glpi:rw
      - ./plugins/webhook:/var/www/html/glpi/plugins/webhook:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Adiciona o host.docker.internal para permitir acesso ao host
      - GLPI_WEBHOOK_URL=http://host.docker.internal:8000/webhook/ticket-closed